export const CHANGE_PAGE = "CHANGE_PAGE";

export const SET_TOTAL_PAGE = "SET_TOTAL_PAGE";

export const CHANGE_SIZE = "CHANGE_SIZE";

export const CHANGE_SORT_FIELD = "CHANGE_SORT_FIELD";

export const CHANGE_SORT_DIRECTION = "CHANGE_SORT_DIRECTION";

export const SEARCH = "SEARCH";
